### ISSUE TITLE
Crash not allowed to start service

### ISSUE THREAD

**Issue by GuillaumeSeg** [google/flutter.plugins#93]
Hello,
I'm getting this error :

```
Shutting down VM
I/flutter (15726): -----------------------------------------------------------
E/AndroidRuntime(15726): FATAL EXCEPTION: main
E/AndroidRuntime(15726): Process: com.my.app, PID: 15726
E/AndroidRuntime(15726): java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.my.app/com.google.flutter.plugins.audiofileplayer.AudiofileplayerService }: app is in background uid UidRecord{aaa2722 u0a737 LAST bg:+4m9s812ms idle change:cached procs:1 seq(0,0,0)}
E/AndroidRuntime(15726): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1650)
E/AndroidRuntime(15726): 	at android.app.ContextImpl.startService(ContextImpl.java:1605)
E/AndroidRuntime(15726): 	at android.content.ContextWrapper.startService(ContextWrapper.java:669)
E/AndroidRuntime(15726): 	at com.google.flutter.plugins.audiofileplayer.AudiofileplayerService$MediaSessionCallback.onPlay(AudiofileplayerService.java:316)
E/AndroidRuntime(15726): 	at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPlay(MediaSessionCompat.java:1405)
E/AndroidRuntime(15726): 	at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPlay(MediaSessionCompatApi21.java:196)
E/AndroidRuntime(15726): 	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1593)
E/AndroidRuntime(15726): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(15726): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(15726): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime(15726): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15726): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(15726): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

I run the service in background on my Oneplus 6 Android 10,

I'm not sure, but shouldn't we use :

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        startForegroundService(new Intent(AudiofileplayerService.this, AudiofileplayerService.class));
} else {
        startService(new Intent(AudiofileplayerService.this, AudiofileplayerService.class));
}
```

inside the onPlay() method from MediaSessionCallback ?
thanks

**Comment by arodriguezgb** [comment]
@GuillaumeSeg Any luck resolving this issue ?

Edit:
I use this plugin on my app and I have a few crashes and ANR on my users but sadly its not something I have been able to replicate with any of my devices or emulators and I have not been able to find a solution, but one less crash is something.

Edit: 
Here is what my users are experiencing the most.
![Screen Shot 2021-01-27 at 11 37 40 AM](https://user-images.githubusercontent.com/53869855/106014952-615f6480-6094-11eb-9c35-5ef42ffe8160.png)

**Comment by mr-mmmmore** [comment]
Before editing `MediaSessionCallback.onPlay` as @GuillaumeSeg did we had crashes when moving the app to background while playing. Doing this edit stopped the crashes to occur.

The problem is explained in this [StackOverflow answer](https://stackoverflow.com/a/46138653). Using `startService` while the app is in the background will fail, for example if trying to play a new file while the app is in the background (using the notification's controls).

We also have added the `foregroundServiceType` flag in our `AndroidManifest` :

```xml
<service android:name="com.google.flutter.plugins.audiofileplayer.AudiofileplayerService"
         android:foregroundServiceType="mediaPlayback"><!------- THIS -->
    <intent-filter>
        <action android:name="android.media.browse.MediaBrowserService" />
    </intent-filter>
    <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON" />
    </intent-filter>
</service>
```
 Our `onPlay` method now looks like this:

```java
public void onPlay() {
  Log.i(TAG, "MediaSessionCallback.onPlay");
  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    startForegroundService(new Intent(AudiofileplayerService.this, AudiofileplayerService.class));
  } else {
    startService(new Intent(AudiofileplayerService.this, AudiofileplayerService.class));
  }
  if (!mediaSession.isActive()) mediaSession.setActive(true);
  Notification notif = buildNotification();
  // Display the notification and place the service in the foreground
  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
    startForeground(NOTIFICATION_ID, notif, ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PLAYBACK);
  } else {
    startForeground(NOTIFICATION_ID, notif);
  }
}
```
I am not an Android developer so I don't guarantee the code but at least it seems to solve our crashes.

**Comment by arodriguezgb** [comment]
Hey @mr-mmmmore , Im going to test your changes but I get many errors building, do you have any idea of whats happening? It doesnt find .Q, or ServiceInfo.

![Screen Shot 2021-02-05 at 8 42 52 PM](https://user-images.githubusercontent.com/53869855/107103104-d8ae9a00-67f2-11eb-9de3-999c5280bec4.png)

Nevermind, i had to change the compileSdkVersion on the build graddle of the player to 29. A quick google search :)

Welp.. that fixes that it doesnt find .Q symbol, but im still missing ServiceInfo.

**Comment by monkeyswarm** [comment]
I'm working on a commit now to use mr-mmmmore suggested changes. (Turns out there are some other issues as well with referencing assets in the flutter assets bundle)
To get .Q and ServiceInfo, you'll have to change the compileSdkVersion in your build.gradle from 28 to 29

**Comment by arodriguezgb** [comment]
@monkeyswarm Yeah just found out about that , thanks. I also found out a few other issues you can see on #95, I think I fixed the issue on my end for now but just removing the action media button when the Notification is Small, but thats not a long term solution. But it helped with crashes for now.

Also if you remember #72 It seems I was able to fix this ANR by adding this to the onCreate method.

```
// TESTING IF THIS HELPS WITH THE CRASHES & ANRS
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      // Display the notification and place the service in the foreground
      //startForeground(NOTIFICATION_ID, notif);
      String CHANNEL_ID = "GentleBirth";
      NotificationChannel channel = new NotificationChannel(CHANNEL_ID,
              "GentleBirth", NotificationManager.IMPORTANCE_NONE);
      ((NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE)).createNotificationChannel(channel);
      Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
              .setSmallIcon(getSmallIconId())
              .setContentTitle("The app is running in the background")
              .setContentText("Swipe for more information or to stop the app.").build();
      startForeground(5544332211, notification);
    }
```

This adds a persistent notification tho, again not Ideal but stopped the ANR's. Wich were at 3% already and flagged bad behaviour. I hope that helps.

**Comment by monkeyswarm** [comment]
What do you mean by 'persistent notification'?

**Comment by arodriguezgb** [comment]
@monkeyswarm 

To avoid those ANR's I added that code which adds this notification when the app starts. I am not very experienced on Android code but I have been reading that the ANR happened because now on Android a foreground service has 5 seconds to be called and if its not called in that certain amount of time it will make the app not respond. 

What I thought was that, that persistent notification allowed the service to start right away and when they played a song they did not ANR if it took 5 seconds or more. Its not specific to a certain device either, but I have personally never got it on my testing to know more. 

I asked some user to beta test my changes and when they said it worked for them I pushed the build, and since then that ANR has not appeared again. 

Attached is a picture of the persistent notification, it goes away when you close the app or play a song. But if its open its there.

![Screenshot_20210206-174911](https://user-images.githubusercontent.com/53869855/107130508-7ca44e00-68a4-11eb-9f06-6edd9f49bf02.jpg)

**Comment by arodriguezgb** [comment]
@monkeyswarm I will remove that custom code and use your new update, I think with these new changes that ANR wont happen again, I feel its similar. It had to do with startForegroundService. Ill update back to close that other bug report aswell if  fixes it and Thanks again.

**Comment by monkeyswarm** [comment]
I've added changes based on mr-mmmmore's code. This is published as version 1.3.3. Please take a look and reopen if the issue continues.

**Comment by mr-mmmmore** [comment]
Thank you! I am not working on this at the moment but I will be testing this part of my app in a few weeks, I'll let you know if I still encounter those problems.

**Comment by volgin** [comment]
This issue is closed, but the plugin does not work with Android 10 (API 29) without a change to AndroidManifest suggested by @mr-mmmmore 

It should be documented and mentioned in the release notes.

**Comment by monkeyswarm** [comment]
Added to the documentation.

**Comment by mr-mmmmore** [comment]
The change in the documentation is not on pub.dev yet, is it?  I mean this part:

```xml
<service android:name="com.google.flutter.plugins.audiofileplayer.AudiofileplayerService"
         android:foregroundServiceType="mediaPlayback"><!------- THIS -->
```

I have upgraded the plugin to the latest version but had forgotten the manifest needed an update (I had stashed all my edits but have then relied only on the plugin update 🙄😅). Not doing so makes the app crash when attempting to play audio, I add the stack trace here in case someone encounters it:

```
java.lang.IllegalArgumentException: foregroundServiceType 0x00000002 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6880)
	at android.app.Service.startForeground(Service.java:744)
	at com.google.flutter.plugins.audiofileplayer.AudiofileplayerService$MediaSessionCallback.onPlay(AudiofileplayerService.java:328)
	at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPlay(MediaSessionCompat.java:1405)
	at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPlay(MediaSessionCompatApi21.java:196)
	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1581)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1360)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:987)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:15068)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3152)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2867)
```
